package org.example.finzin.ai;

import org.example.finzin.entity.CategoryEntity;
import org.example.finzin.repository.CategoryRepository;
import org.example.finzin.repository.TransactionRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Surfaces plain-language observations about month-over-month and trend changes in the user's own
 * transactions. Every insight is derived from a threshold comparison over real sums from
 * {@link TransactionRepository} — nothing here is generated by the model, so the AI can quote these
 * verbatim instead of trying to notice patterns itself.
 */
@Service
public class InsightService {

    private static final double MOM_NOTABLE_PERCENT = 15.0;
    private static final double MOM_HIGH_PERCENT = 30.0;
    private static final double UNUSUAL_SPEND_MULTIPLIER = 1.5;
    private static final int TREND_MONTHS = 3;

    private final TransactionRepository transactionRepository;
    private final CategoryRepository categoryRepository;

    public InsightService(TransactionRepository transactionRepository, CategoryRepository categoryRepository) {
        this.transactionRepository = transactionRepository;
        this.categoryRepository = categoryRepository;
    }

    public record Insight(String title, String description, String priority, String category,
                           LocalDate date, String source, double confidence) {}

    public List<Insight> generateInsights(Long userId) {
        List<Insight> insights = new ArrayList<>();
        YearMonth current = YearMonth.now();
        YearMonth previous = current.minusMonths(1);
        int throughDay = LocalDate.now().getDayOfMonth();

        for (CategoryEntity cat : categoryRepository.findByUserId(userId)) {
            double currentSpend = monthToDateSum(userId, "expense", cat.getId(), current, throughDay);
            double previousSpend = monthToDateSum(userId, "expense", cat.getId(), previous, throughDay);
            addMoMInsight(insights, cat.getName(), currentSpend, previousSpend);

            double trailingAvg = trailingAverage(userId, "expense", cat.getId(), current);
            addUnusualSpendInsight(insights, cat.getName(), currentSpend, trailingAvg);
        }

        addIncomeInsight(insights, monthToDateSum(userId, "income", null, current, throughDay), monthToDateSum(userId, "income", null, previous, throughDay));
        addSavingsMoMInsight(insights, monthToDateSum(userId, "savings", null, current, throughDay), monthToDateSum(userId, "savings", null, previous, throughDay));
        addSavingsUnusualInsight(insights, monthToDateSum(userId, "savings", null, current, throughDay), trailingAverage(userId, "savings", null, current));

        return insights;
    }

    private void addMoMInsight(List<Insight> insights, String categoryName, double current, double previous) {
        if (previous <= 0) return;
        double changePercent = ((current - previous) / previous) * 100;
        if (Math.abs(changePercent) < MOM_NOTABLE_PERCENT) return;

        String direction = changePercent > 0 ? "increased" : "decreased";
        insights.add(new Insight(
                categoryName + " spending " + direction + " " + formatPercent(changePercent) + "% this month",
                categoryName + " expenses " + direction + " from " + formatAmount(previous) + " to " + formatAmount(current)
                        + " compared to the same point last month.",
                Math.abs(changePercent) >= MOM_HIGH_PERCENT ? "HIGH" : "MEDIUM",
                categoryName,
                LocalDate.now(),
                "TRANSACTIONS_MOM",
                0.85));
    }

    private void addUnusualSpendInsight(List<Insight> insights, String categoryName, double current, double trailingAvg) {
        if (trailingAvg <= 0 || current <= trailingAvg * UNUSUAL_SPEND_MULTIPLIER) return;
        insights.add(new Insight(
                categoryName + " spending was unusually high",
                "You spent " + formatAmount(current) + " on " + categoryName + " this month, well above your "
                        + TREND_MONTHS + "-month average of " + formatAmount(trailingAvg) + ".",
                "HIGH",
                categoryName,
                LocalDate.now(),
                "TRANSACTIONS_TREND",
                0.8));
    }

    private void addIncomeInsight(List<Insight> insights, double current, double previous) {
        if (previous <= 0) return;
        double changePercent = ((current - previous) / previous) * 100;
        if (Math.abs(changePercent) < MOM_NOTABLE_PERCENT) return;

        insights.add(new Insight(
                changePercent > 0 ? "Your income increased" : "Your income decreased",
                "Income " + (changePercent > 0 ? "rose" : "fell") + " from " + formatAmount(previous) + " to "
                        + formatAmount(current) + " (" + formatPercent(changePercent) + "%) compared to the same point last month.",
                Math.abs(changePercent) >= MOM_HIGH_PERCENT ? "HIGH" : "MEDIUM",
                "Income",
                LocalDate.now(),
                "TRANSACTIONS_INCOME",
                0.85));
    }

    private void addSavingsMoMInsight(List<Insight> insights, double current, double previous) {
        if (previous <= 0) return;
        double changePercent = ((current - previous) / previous) * 100;
        if (Math.abs(changePercent) < MOM_NOTABLE_PERCENT) return;

        insights.add(new Insight(
                changePercent > 0
                        ? "You saved " + formatPercent(changePercent) + "% more than last month"
                        : "You saved " + formatPercent(Math.abs(changePercent)) + "% less than last month",
                "Savings contributions " + (changePercent > 0 ? "rose" : "fell") + " from " + formatAmount(previous)
                        + " to " + formatAmount(current) + " compared to the same point last month.",
                "MEDIUM",
                "Savings",
                LocalDate.now(),
                "TRANSACTIONS_SAVINGS",
                0.85));
    }

    private void addSavingsUnusualInsight(List<Insight> insights, double current, double trailingAvg) {
        if (trailingAvg <= 0 || current <= trailingAvg * UNUSUAL_SPEND_MULTIPLIER) return;
        insights.add(new Insight(
                "You transferred more money to savings than usual",
                "You saved " + formatAmount(current) + " this month, above your " + TREND_MONTHS
                        + "-month average of " + formatAmount(trailingAvg) + ".",
                "LOW",
                "Savings",
                LocalDate.now(),
                "TRANSACTIONS_SAVINGS_TREND",
                0.8));
    }

    /** Average of the {@link #TREND_MONTHS} calendar months immediately before {@code current} (never including it). */
    private double trailingAverage(Long userId, String type, Long categoryId, YearMonth current) {
        double sum = 0;
        for (int i = 1; i <= TREND_MONTHS; i++) {
            sum += monthSum(userId, type, categoryId, current.minusMonths(i));
        }
        return sum / TREND_MONTHS;
    }

    private double monthSum(Long userId, String type, Long categoryId, YearMonth month) {
        LocalDateTime start = month.atDay(1).atStartOfDay();
        LocalDateTime end = month.plusMonths(1).atDay(1).atStartOfDay();
        return sum(userId, type, categoryId, start, end);
    }

    /**
     * Sums {@code day 1 .. min(throughDay, month length)} of the given month — used for
     * month-over-month comparisons so an in-progress current month is compared against the *same*
     * number of days last month, not a full 30 days against a partial one (which would make every
     * category look like it "dropped" for the first three weeks of every month).
     */
    private double monthToDateSum(Long userId, String type, Long categoryId, YearMonth month, int throughDay) {
        int clampedDay = Math.min(throughDay, month.lengthOfMonth());
        LocalDateTime start = month.atDay(1).atStartOfDay();
        LocalDateTime end = month.atDay(clampedDay).plusDays(1).atStartOfDay();
        return sum(userId, type, categoryId, start, end);
    }

    private double sum(Long userId, String type, Long categoryId, LocalDateTime start, LocalDateTime end) {
        Double sum = categoryId == null
                ? transactionRepository.sumByUserIdAndTypeAndDateRange(userId, type, start, end)
                : transactionRepository.sumByUserIdAndTypeAndCategoryAndDateRange(userId, type, categoryId, start, end);
        return sum == null ? 0 : sum;
    }

    private static String formatPercent(double value) {
        return String.format(Locale.ROOT, "%.0f", Math.abs(value));
    }

    private static String formatAmount(double value) {
        return String.format(Locale.ROOT, "%.0f", value);
    }
}
